version: 2
registries:
  npm-npmjs:
    type: npm-registry
    url: https://registry.npmjs.org
    token: ${{ secrets.NPM_TOKEN_READ_ONLY_DEPENDABOT }}
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "America/New_York"
    commit-message: # Prefix all commit messages with "actions: "
      prefix: "actions"
    labels:
      - "actions"
      - "dependabot"
    assignees:
      - "jeffsays"
    reviewers:
      - "jeffsays"
    groups:
      actions-deps:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/"
    registries:
      - npm-npmjs
    schedule:
      interval: "daily"
      time: "07:30"
      timezone: "America/New_York"
    commit-message: # Prefix all commit messages with "npm: "
      prefix: "npm"
    labels:
      - "dependencies"
      - "dependabot"
    assignees:
      - "jeffsays"
    reviewers:
      - "jeffsays"
    groups:
      cumulus-prod-deps:
        dependency-type: "production"
      cumulus-dev-deps:
        dependency-type: "development"
    allow: # Provide version updates for cumulusds packages
      - dependency-name: "@cumulusds/*"
        dependency-type: "all"
  - package-ecosystem: "npm"
    directory: "/"
    registries:
      - npm-npmjs
    schedule:
      interval: "daily"
      time: "07:30"
      timezone: "America/New_York"
    commit-message: # Prefix all commit messages with "npm security: "
      prefix: "npm security"
    labels:
      - "dependencies"
      - "dependabot"
    assignees:
      - "jeffsays"
    reviewers:
      - "jeffsays"
    groups:
      prod-deps-sec:
        dependency-type: "production"
      dev-deps-sec:
        dependency-type: "development"
    allow: # Provide security updates, but not version updates, for open-source packages
      - dependency-name: "*"
        dependency-type: "all"
    ignore: # Issue security updates, but not regular updates, for public packages
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
          - version-update:semver-patch
    target-branch: master # specifying target-branch in one configuration and not the other is a loophole that allows
    # us to have two configurations for "npm".  see open feature request:
    # https://github.com/dependabot/dependabot-core/issues/1778#issuecomment-1988140219
