name: ci-cd

on:
  push:
    branches:
      - '**/*'
  pull_request:
  release:
    types: [released]

jobs:
  unit:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node: [10, 12, 13, 14]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install NPM credentials
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install NPM Packages
        run: yarn install --frozen-lockfile
      - name: Check licenses
        run: yarn build:license-checker
      - name: Test
        run: yarn test
      - uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          author_name: ${{ github.repository }} ${{ github.workflow }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        if: always()
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: var
          path: var
        if: always()
  publish:
    runs-on: ubuntu-18.04
    needs: unit
    if: github.event_name == 'release'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install NPM credentials
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install NPM Packages
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Publish
        run: npm publish
        if: startsWith(github.event.ref, 'refs/tags')
